# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  # ðŸŸ¢ Tell Air where your main Go file lives
 cmd = "go build -o ./tmp/main.exe ./cmd/api"
bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor",".git"]

# Optional: delay before rebuilding after save
delay = 1000
